// Barrel re-export — all existing `import { ... } from '@/lib/db'` continue to work.
export * from './db.shared'
export * from './db.profile'
export * from './db.stats'
export * from './db.notifications'
export * from './db.groups'
export * from './db.permissions'
export * from './db.exams'
export * from './db.homeworks'
export * from './db.parent'
export * from './db.messages'
export * from './db.payments'
export * from './db.misc'
